### ISSUE TITLE
wide aspect-ratio images don't appear in album teaser

### ISSUE THREAD

**Issue by CantStopMyBrain** [StigNygaard/Stigs_Flickr_Fixr#4]
The title/heading photo for one of my albums has an width:height ratio of about 4:1; it does not appear in the album teaser sidebar, which instead just displays an empty box for that album. It's only an assumption that the aspect ratio is the cause of the problem, but it gives you a starting point ;)

If you want to see it in (in)action, my flickr home page is https://www.flickr.com/photos/lite_play/ and the album is currently the 3rd one down, named "hadley".

**Comment by StigNygaard** [comment]
Hi @CantStopMyBrain 
The way Flickr Fixr feature work is to read the "normal" albumlist-page in background to find title, links and "header-images" for albums. But Fixr's teaser-column doesn't use the exact same header-images, but modifies the image-addresses a way that usually will give the smaller 150x150 square versions. It does however not work in that particular case, and I think you are right that it is probably related to the "extreme" aspect-ratio.
I will give it a closer look another day, and see if I can find a way for it to work in this case too.
Thanks for reporting.

**Comment by StigNygaard** [comment]
Hi @CantStopMyBrain 
FYI, I have fixed this issue with latest commit to this repository. So a fixed version of Flickr Fixr is one stop closer. But I plan to add another update before releasing an official new version of Flickr Fixr.

**Comment by StigNygaard** [comment]
@CantStopMyBrain 
A new bugfix release is roiling out. Includes the fix for this issue,
Available now for Firefox (1.18.1) and hopefully within a week also for Chrome & Edge (2.3.1).
